### PR TITLE
Support OR condition on multiple properties for one type

### PR DESCRIPTION
**Pull request by FrankSzendzielarz**
Allow a type to be instantiated if one or more properties are present. eg:

```cs 
    [JsonConverter(typeof(JsonSubtypes))]
    [JsonSubtypes.FallBackSubType(typeof(Dog))]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(Cat), "MeowSoundVolume")]
    [JsonSubtypes.KnownSubTypeWithProperty(typeof(Cat), "PurrSoundIntensity")]
```

### CODE REVIEW

**Comment by manuc66** [comment]
Hi,

Thanks for your pull request !

Could you add some tests, so that this feature will remains across versions?

**Comment by FrankSzendzielarz** [comment]
Hi Emmanuel,

Sure, will do.

**Comment by FrankSzendzielarz** [comment]
Actually, this PR needs some more work. I will update things and add tests and get back to you.

**Comment by FrankSzendzielarz** [comment]
OK done. Fixed an error in my PR and then added tests.

**Comment by manuc66** [comment]
Thanks for contributing 🎉

**Comment by FrankSzendzielarz** [comment]
@manuc66  Hi there. Pls could you push the new NuGet ? Need it for an OSS library I am working on.

**Comment by manuc66** [comment]
Published with version 1.9.0

**Comment by FrankSzendzielarz** [comment]
Epic.

**Pull request merged**
